version: 1.0.{build}
image: Visual Studio 2017
shallow_clone: true
environment:
  matrix:
    - configuration: Debug
    - configuration: Release
platform:
  - x64
  - Win32
branches:
  except:
    - d3d12
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#environment:
#  appveyor_rdp_password:
#    secure: isPeZD3/K+h+07yX2nK8kQ==
before_build:
  - ps: .\scripts\MakeVS2017.bat
after_build:
- cmd: 7z a FluxGame_%PLATFORM%_%CONFIGURATION%_%APPVEYOR_BUILD_NUMBER%.zip .\Build\FluxGame_%PLATFORM%_%CONFIGURATION%\* .\FluxGame\Resources\
build:
  project: FluxEngine.sln
  parallel: true
  verbosity: minimal
artifacts:
  - path: 'FluxGame_$(PLATFORM)_$(CONFIGURATION)_$(APPVEYOR_BUILD_NUMBER).zip'
    name: Build_$(PLATFORM)_$(CONFIGURATION)_$(APPVEYOR_BUILD_NUMBER)